<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE modules [
    <!ELEMENT modules (module*)>

    <!ELEMENT module ANY>
    <!ATTLIST module
        name CDATA #REQUIRED
    >
]>

<!--
    Here all official modules.
	Read the wiki about Modules to know how to make a module for misTET. http://github.com/lostpassword/misTET/wiki
-->

<modules>
	<module name="security"></module>
	<module name="blog"></module>
	<module name="logger"></module>
	<module name="markdown"></module>
	<module name="SyntaxHighlighter"></module>
</modules>
