<?xml version="1.0"?> 
<!DOCTYPE pages [
	<!ELEMENT pages (page+)>
	<!ELEMENT page (go*)>
	<!ELEMENT page (text*)>
	
	<!ELEMENT page ANY>
	<!ATTLIST page
		id	ID	#REQUIRED
	>
	<!ELEMENT go ANY>
	<!ATTLIST go
		href	CDATA	#REQUIRED
		lan		CDATA	#IMPLIED
		text	CDATA	#REQUIRED
		after	CDATA	#IMPLIED
	>
	
	<!ELEMENT text ANY>
	<!ATTLIST text
		href	CDATA	#REQUIRED
		lan		CDATA	#IMPLIED
	>
]>
<!--
To create a new page, just use <page> node with the page content. The 
attribute `id` has to be the same you specified in menu.xml. Through <go>
node you can create a link to an extern file, and through the attribute
`lan` you can include sources. The attribute `text` is equivalent to 
<a href="">text</a>, while the attribute `after` specifies the text to show
jsut after the link. You can use `text` node to import a file in a page,
and use the `lan` attribute to include sources.

WARNING: Don't use exclusively html code in your pages, it can cause some
	 	 problems.
-->
<pages>
	<page id = 'home'>
		<![CDATA[
			This site is for everybody who follows my project. It will be updated everytime
			another version of misTET is released. You can visit the blog page to view all the
			news.
		]]>
	</page>
	<page id = 'admin'>
	</page>
	<page id = 'blog'>
	</page>
	<page id = 'features'>
		<![CDATA[
			In this section there are some of the features of this cms, like including an extern file,
			using sources, and using the `go` attribute.
		]]>
	</page>
	<page id = 'extern'>
		<![CDATA[
			This is an example of how including an extern file, with Syntax Highlighting :P
		]]>
		<text href = "notes.txt" lan = "python"></text>
	</page>
	<page id = 'PHP'>
		<![CDATA[
			You can use the following syntax:<br>
			<pre id = 'code'>#id&page=name.php</pre><br>
			name.php: name of the page in /res/files/stat<br>
			The output is not the source, but what the server says getting the PHP page. Here's an example:<br>
		]]>
		<go href = "/res/files/stat/lol.php" text = "View" after = " ~ This is a PHP page which shows your IP"></go>
	</page>
	<page id = 'go'>
		<![CDATA[
			Using `go` attribute. As you can see, you can also include a file using:<br>
			<pre id = 'code'>#id&page=pageRef</pre><br>where pageRef is a link of a file in this server :P<br><br>
		]]>
		<go href = "/res/files/stat/notes.txt" lan = "python" text = "View" after = " ~ This is an external link, a source"></go>
		<go href = "/res/files/stat/well" text = "View" after = " ~ This is an external link, a simple file"></go>
	</page>
	<page id = 'nigger'>
		<![CDATA[
			NIGGER page, this is just useless.
		]]>
	</page>
</pages>
